### ISSUE TITLE
Add Ice and Fire: Dragons Support

### ISSUE THREAD

**Issue by wendall911** [wendall911/TCIntegrations#39]
From [Raphtio](https://legacy.curseforge.com/members/raphtio) on CurseForge:

I think traits should be very similar to this in the mod itself and use same items:

[Dragon Bone Sword | Ice and Fire Mod Wiki | Fandom](https://ice-and-fire-mod.fandom.com/wiki/Dragon_Bone_Sword)

[Myrmex Stinger Sword | Ice and Fire Mod Wiki | Fandom](https://ice-and-fire-mod.fandom.com/wiki/Myrmex_Stinger_Sword)

[Hydra | Ice and Fire Mod Wiki | Fandom](https://ice-and-fire-mod.fandom.com/wiki/Hydra) - poison effect (Hydra fang)

[Witherbone | Ice and Fire Mod Wiki | Fandom](https://ice-and-fire-mod.fandom.com/wiki/Witherbone) - withering effect

If they will work with ranged weapons will be awesome.

Only for swords:

[Phantasmal Blade | Ice and Fire Mod Wiki | Fandom](https://ice-and-fire-mod.fandom.com/wiki/Phantasmal_Blade)

Support for Ice/Fire/Lightning Dragonsteel armor materials.

**Comment by wendall911** [comment]
* Adds "**Flamed**" upgrade modifier - Weapons
   * Knocks back target
   * Sets target on fire for 5 seconds
   * Bonus damage against Ice Dragons
 * Adds "**Iced**" upgrade modifier - Weapons
   * Knocks back target
   * Adds slowness to target for 5 seconds
   * Bonus damage against Fire Dragons
 * Adds "**Zapped**" upgrade modifier - Weapons
   * Knocks back target
   * Lighting strikes hit target
   * Bonus damage against Ice and Fire Dragons
 * Adds "**Phantasmal**" upgrade modifier - Swords
   * Launches Ghost Sword when swinging sword in air

**Comment by ffuentesm** [comment]
Hum...
Would be nice if you could add part materials from Ice and Fire. 
Like craft Phantamalk ingot by allowing a material with liquid soul. And have Ectoplasm be smelted into liquid soul. 
Also make so that only heads can be crafted from it. then place the Phantasmal trait on the material

Maybe a way to place the Dragon Forge Aperture to the Smeltery so you can use dragon breath as a fuel source instead of a fuel tank, so you can alloy dragon steel inside a smeltery by pouring dragon blood and molten iron inside of it. 

You could also make so that some upgrade modifiers are actually material traits for exclusive Ice and fire parts. 
Have some materials be exclusive for a specific tool part, like how you can only use chain to make a tool bind. 
That way you can have Stymphalian Bird Feather to only make the blade parts. Or add the Myrmex Chitin as tool and armor materials. 

Also, add withered bone and Necrotic Bone interchangeably.

**Comment by wendall911** [comment]
I already added material support for this, just forgot to tag the commit. There are existing integrations as well.

@ffuentesm as for your request. Tinkers' doesn't work in a way that would allow integration of the dragon forge aperture, however, I did add the dragonsteel materials. That isn't really feasable. As for the custom material and part stuff, that is really way outside of the scope of how I want to do integrations. That would be an entirely separate mod or modpack to do that stuff. I don't have any plans to change this integration or others at this point. Possibly in the future, but not for 1.19.2, and I have no plans to backport anything to 1.18.2.

I can add withered bone to the recipe modifier tag.
