### ISSUE TITLE
Add: Smelting integration to Ice and Fire Items into fluids

### ISSUE THREAD

**Issue by ffuentesm** [wendall911/TCIntegrations#59]
Since we already have the smelting of Dragon Stell into fluid, could you add the smelting of the Silver and Copper gear? 
Mostly looking at the Dragon armor smelting. As I have no idea of what to do with the extra ones I found.

**Comment by wendall911** [comment]
Hmm, yeah, that's an issue we ran into on our modpack. I just manually added the stuff. I think this would be a good addition. Thanks for asking! I'll get it added soon. In the meanwhile, if you want the data for silver, you can find it here: https://github.com/wendall911/TinkerSurvivalModpack/tree/1.19.2/global_packs/required_data/tinkersurvival/data/tconstruct/recipes/smeltery/melting/metal/silver

**Comment by ffuentesm** [comment]
Thanks, I know this might be outside the scope of the mod, but I made some compact material options regarding some of the special weapons and other armours/tools. Not sure what to do with Sapphires as "water theme" modifiers are already covered in base TIC

![image](https://github.com/wendall911/TCIntegrations/assets/44974827/37025df7-b941-4856-978a-8ef4cbe26a58)

**Comment by wendall911** [comment]
Ok, I've basically not taken the route of patterns or Alloys for mod management reasons. It is far less complicated to maintain and create modifiers. I know this is traditionally how expansion mods have done this, in that they add new functionality on top of the mod. I'm trying to allow for core mod mechanics to be available without inventing new stuff. For example, Phantasmal exists already as a modifier. It follows the recipe cost in IFD. Having a new alloy doesn't make sense to me, since it isn't staying true to IFD, but actually acting as an IFD expansion.

This looks like some really great ideas. The idea is integration (hence the mod name) not expansion.

**Comment by ffuentesm** [comment]
I understand, easier to add modifiers than new textures and tool parts. 
Also why I mention modifier ideas there, Pixie Wings, Cockatrice Eye, Amphithere Feather as ideas. 
Sorry for my ramble, When I think TiC, I think of "full weapon replacement" kind of why I am trying to replace vanilla gear with TiC ones. Such as chest loots, villager trades, mob gear. So I enjoy trying to come up with compact forms.

**Comment by wendall911** [comment]
New version 1.19.2-2.0.21.5 is up on curseforge/modrinth
